package behavior.visitor.dengxt;

/**
 * Generated by StarUML(tm) Java Add-In
 * @ Project : The Best Practice
 * @ File Name : BaseRule.java
 * @ Date : 2013-8-20
 * @author dengxiaotao@gmail.com
 */
public class ImplMatchPattern implements IVisitor <Boolean>{
	
	@Override
	public  Boolean visit(IRule rule, String target, int index) {
		
		if(rule == null || target == null) return false; 
		
		return rule.match(this, target, index++);
	}
}
