package behavior.visitor.dengxt;


/**
 * Generated by StarUML(tm) Java Add-In
 * @ Project : The Best Practice
 * @ File Name : ImplPrintPattern.java
 * @ Date : 2013-8-20
 * @author dengxiaotao@gmail.com
 *
 */
public class ImplPrintPattern implements IVisitor<String> {
	
	private IRule rule = null;;

	@Override
	public String visit(IRule r, String target, int index) {
		
		if(rule == null || index>target.length() -1) return ""; 
		
		rule = r;
		StringBuffer buffer = new StringBuffer();
		do{
			if(rule.match(this, target, index)){
				buffer.append(String.format("Rule:%s Match:%s", rule.rule(), target.charAt(index)));
				index++;
			}
		}while((rule = rule.next) != null);
		
		return buffer.toString();
	}
	
}
