package behavior.visitor.dengxt;

/**
 * Generated by StarUML(tm) Java Add-In
 * @ Project : The Best Practice
 * @ File Name : Vistor.java
 * @ Date : 2013-8-20
 * @ Date : 2013-8-20
 * @author dengxiaotao@gmail.com
 *
 */
public interface IVisitor<T>{
	
	public T visit(IRule next, String target, int index);
	
	/**
	 * Factory to create new instances of concrete object record
	 */
	interface Factory {
		/**
		 * Creates a new rule of pattern for String matching;
		 * 
		 * @param pattern a matching pattern.
		 * @return IRule chain
		 */
		IRule buildRule(String pattern);
	}
}
