package behavior.visitor.dengxt;

/**
 * Generated by StarUML(tm) Java Add-In
 *
 * @ Project : The Best Practice
 * @ File Name : BaseRule.java
 * @ Date : 2013-8-20
 * @author dengxiaotao@gmail.com
 */
public class RuleDot extends IRule {

    private static final char RULE = '.';

    public static RuleDot newInstance() {

        return new RuleDot();
    }

    /**
     * Constructor for File.
     *
     * @param primaryKey
     * @param attributes
     */
    private RuleDot() {
    }

    @Override
    public boolean match(IVisitor<?> visitor, String target, int index) {
        
        if (index >= target.length()) {
            return false;
        }

        if (next != null) {
            return next.match(visitor, target, index + 1);
        }

        return index == target.length() - 1;

//        if (next != null && index < target.length() - 1) {
//            return next.match(visitor, target, index + 1);
//        }
//
//        if (index == target.length()) {
//            return next == null ? true : next.match(visitor, target, index + 1);
//        }
//
//        return false;
    }

    public String toString() {
        return "." + ((next == null) ? "#" : next.toString());
    }
}
