package behavior.visitor.dengxt;

/**
 * Generated by StarUML(tm) Java Add-In
 * @ Project : The Best Practice
 * @ File Name : BaseRule.java
 * @ Date : 2013-8-20
 * @author dengxiaotao@gmail.com
 */
public class RuleStar extends IRule {
	
	private static final char RULE = '*';
	
	public static RuleStar newInstance() {
		
		return new RuleStar();
	}
	
	/**
	 * Constructor for File.
	 * @param primaryKey
	 * @param attributes
	 */
	private RuleStar() {
		
	}

	
	@Override
	public boolean match(IVisitor<?> visitor, String target, int index) {
		
		if(index >= target.length()) return true;
                
                if(next == null) return true;
                
		boolean match = false;
		
		while(next != null && !match && index < target.length()){
			match = next.match(visitor, target, index++);
		}
		
		return match;
	}
        
        public String toString(){
            return "*" + ((next == null)? "#" :next.toString());
        }
}
